[project]
name = "hexlet-code"
version = "0.1.0"
description = "Task Manager built with Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=5.2,<5.3",
    "django-bootstrap5>=26.2",
    "django-filter>=26.1",
    "gunicorn>=26.0.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.2",
    "rollbar>=1.4.0",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
    "coverage>=7.15.3",
    "ruff>=0.16.1",
]

[tool.ruff]
line-length = 88
exclude = [
    "*/migrations/*",
    "task_manager/settings.py",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
