sonar.organization=clownya57-brain-games
sonar.projectKey=clownya57_python-project-52
sonar.projectName=Task Manager

sonar.sources=task_manager,users,statuses,labels,tasks,templates
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/tests.py,**/test_*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/migrations/**,**/tests.py,**/test_*.py,task_manager/asgi.py,task_manager/wsgi.py

sonar.sourceEncoding=UTF-8
